function lhs_graph() {
    return {
        directed: false,
        vertices: {
            "B/P": { x: 325, y: 205, class: "" },
            "D": { x: 43, y: 294, class: "" },
            "DD": { x: 345, y: 303, class: "" },
            "EF": { x: 224, y: 313, class: "" },
            "H": { x: 170, y: 216, class: "" },
            "HB": { x: 126, y: 166, class: "" },
            "HH": { x: 183, y: 135, class: "" },
            "KI": { x: 185, y: 84, class: "" },
            "M": { x: 251, y: 508, class: "" },
            "MD": { x: 250, y: 235, class: "" },
            "MZ": { x: 90, y: 398, class: "" },
            "S": { x: 141, y: 465, class: "" },
            "SB": { x: 41, y: 426, class: "" },
            "SN": { x: 240, y: 132, class: "" },
            "WI": { x: 115, y: 360, class: "" },
        },
        edges: [
            { from: "B/P", to: "DD", weight: 195, weightDistance: 15, class: "" },
            { from: "B/P", to: "MD", weight: 155, class: "" },
            { from: "B/P", to: "SN", weight: 215, class: "" },
            { from: "D", to: "EF", weight: 400, class: "" },
            { from: "D", to: "H", weight: 280, weightDistance: 8, class: "" },
            { from: "D", to: "HB", weight: 295, class: "" },
            { from: "D", to: "SB", weight: 280, weightDistance: -15, class: "" },
            { from: "D", to: "WI", weight: 205, class: "" },
            { from: "DD", to: "EF", weight: 215, class: "" },
            { from: "DD", to: "M", weight: 459, weightDistance: 25, class: "" },
            { from: "DD", to: "MD", weight: 230, class: "" },
            { from: "EF", to: "MD", weight: 170, class: "" },
            { from: "EF", to: "H", weight: 250, class: "" },
            { from: "EF", to: "M", weight: 415, weightDistance: -15, class: "" },
            { from: "EF", to: "S", weight: 340, class: "" },
            { from: "EF", to: "WI", weight: 280, class: "" },
            { from: "H", to: "HB", weight: 115, weightDistance: -15, class: "" },
            { from: "H", to: "HH", weight: 150, weightDistance: -15, class: "" },
            { from: "H", to: "MD", weight: 145, class: "" },
            { from: "HB", to: "HH", weight: 125, class: "" },
            { from: "HH", to: "KI", weight: 95, class: "" },
            { from: "HH", to: "SN", weight: 110, class: "" },
            { from: "MD", to: "SN", weight: 215, weightDistance: 15, class: "" },
            { from: "MZ", to: "S", weight: 210, class: "" },
            { from: "MZ", to: "SB", weight: 150, class: "" },
            { from: "MZ", to: "WI", weight: 15, weightDistance: -20, class: "" },
            { from: "S", to: "M", weight: 230, class: "" },
            { from: "S", to: "SB", weight: 265, class: "" }
        ]
    }
}